name: Robert Harshman
favicon: null
layout_spectrum: 0.5736571492161602
typography_spectrum: 0.6171835674904287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7483127480372787
  lightness: 0.9726366505492479
  saturation: 0.9986523820552975
  rhythmicContrast: 0.4558583025354892
purpose: []
